package org.openmrs.module.savicsgmao.api.entity;

import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 * Agent generated by hbm2java
 */
public class Agent extends BaseOpenmrsData {
	
	private Integer agentId;
	
	private Department department;
	
	private SiteLocation siteLocation;
	
	private String uuid;
	
	private String fullName;
	
	private String agentAddress;
	
	private String phoneNumber;
	
	private String rollNumber;
	
	private byte isExternal;
	
	private Set Maintenances = new HashSet(0);
	
	public Integer getAgentId() {
		return this.agentId;
	}
	
	public void setAgentId(Integer agentId) {
		this.agentId = agentId;
	}
	
	public Department getDepartment() {
		return this.department;
	}
	
	public void setDepartment(Department Department) {
		this.department = Department;
	}
	
	public SiteLocation getSiteLocation() {
		return this.siteLocation;
	}
	
	public void setSiteLocation(SiteLocation SiteLocation) {
		this.siteLocation = SiteLocation;
	}
	
	public String getFullName() {
		return this.fullName;
	}
	
	public void setFullName(String fullName) {
		this.fullName = fullName;
	}
	
	public String getAgentAddress() {
		return this.agentAddress;
	}
	
	public void setAgentAddress(String agentAddress) {
		this.agentAddress = agentAddress;
	}
	
	public String getPhoneNumber() {
		return this.phoneNumber;
	}
	
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	
	public String getRollNumber() {
		return this.rollNumber;
	}
	
	public void setRollNumber(String rollNumber) {
		this.rollNumber = rollNumber;
	}
	
	public byte getIsExternal() {
		return this.isExternal;
	}
	
	public void setIsExternal(byte isExternal) {
		this.isExternal = isExternal;
	}
	
	public Set getMaintenances() {
		return this.Maintenances;
	}
	
	public void setMaintenances(Set Maintenances) {
		this.Maintenances = Maintenances;
	}
	
	@Override
	public User getCreator() {
		return creator;
	}
	
	@Override
	public void setCreator(User creator) {
		this.creator = creator;
	}
	
	@Override
	public Integer getId() {
		return getAgentId();
	}
	
	@Override
	public void setId(Integer id) {
		setAgentId(id);
	}
	
}
