package org.openmrs.module.savicsgmao.api.entity;

// Generated Mar 25, 2021 1:50:49 PM by Hibernate Tools 4.3.1
import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 * Agent generated by hbm2java
 */
public class Agent extends BaseOpenmrsData {
	
	private Integer agentId;
	
	private String uuid;
	
	private String fullName;
	
	private String agentAddress;
	
	private String phoneNumber;
	
	private String rollNumber;
	
	private byte isExternal;
	
	private Integer departmentId;
	
	private Integer siteLocationId;
	
	public Agent() {
	}
	
	public Agent(String fullName, String agentAddress, String phoneNumber, byte isExternal) {
		this.fullName = fullName;
		this.agentAddress = agentAddress;
		this.phoneNumber = phoneNumber;
		this.isExternal = isExternal;
	}
	
	public Agent(String fullName, String agentAddress, String phoneNumber, String rollNumber, byte isExternal,
	    Integer departmentId, Integer siteLocationId) {
		this.fullName = fullName;
		this.agentAddress = agentAddress;
		this.phoneNumber = phoneNumber;
		this.rollNumber = rollNumber;
		this.isExternal = isExternal;
		this.departmentId = departmentId;
		this.siteLocationId = siteLocationId;
	}
	
	public Integer getAgentId() {
		return this.agentId;
	}
	
	public void setAgentId(Integer agentId) {
		this.agentId = agentId;
	}
	
	public String getFullName() {
		return this.fullName;
	}
	
	public void setFullName(String fullName) {
		this.fullName = fullName;
	}
	
	public String getAgentAddress() {
		return this.agentAddress;
	}
	
	public void setAgentAddress(String agentAddress) {
		this.agentAddress = agentAddress;
	}
	
	public String getPhoneNumber() {
		return this.phoneNumber;
	}
	
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	
	public String getRollNumber() {
		return this.rollNumber;
	}
	
	public void setRollNumber(String rollNumber) {
		this.rollNumber = rollNumber;
	}
	
	public byte getIsExternal() {
		return this.isExternal;
	}
	
	public void setIsExternal(byte isExternal) {
		this.isExternal = isExternal;
	}
	
	public Integer getDepartmentId() {
		return this.departmentId;
	}
	
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}
	
	public Integer getSiteLocationId() {
		return this.siteLocationId;
	}
	
	public void setSiteLocationId(Integer siteLocationId) {
		this.siteLocationId = siteLocationId;
	}
	
	@Override
	public int hashCode() {
		int hash = 0;
		hash += (agentId != null ? agentId.hashCode() : 0);
		return hash;
	}
	
	@Override
	public boolean equals(Object object) {
		// TODO: Warning - this method won't work in the case the id fields are not set
		if (!(object instanceof Agent)) {
			return false;
		}
		Agent other = (Agent) object;
		if ((this.agentId == null && other.agentId != null) || (this.agentId != null && !this.agentId.equals(other.agentId))) {
			return false;
		}
		return true;
	}
	
	@Override
	public String getUuid() {
		return uuid;
	}
	
	@Override
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	@Override
	public User getCreator() {
		return creator;
	}
	
	@Override
	public void setCreator(User creator) {
		this.creator = creator;
	}
	
	@Override
	public String toString() {
		return "org.openmrs.module.savicsgmao.api.entity.GmaoAgent[ agentId=" + agentId + " ]";
	}
	
	@Override
	public Integer getId() {
		return getAgentId();
	}
	
	@Override
	public void setId(Integer id) {
		setAgentId(id);
	}
	
}
