package org.openmrs.module.savicsgmao.api.entity;

import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 * Departmentt generated by hbm2java
 */
public class Department extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer departmentId;
	
	private String uuid;
	
	private String departmentName;
	
	private String departmentCode;
	
	private Set Agents = new HashSet(0);
	
	private Set MaintenanceRequests = new HashSet(0);
	
	private Set Equipments = new HashSet(0);
	
	public Integer getDepartmentId() {
		return this.departmentId;
	}
	
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}
	
	public String getDepartmentName() {
		return this.departmentName;
	}
	
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}
	
	public String getDepartmentCode() {
		return this.departmentCode;
	}
	
	public void setDepartmentCode(String departmentCode) {
		this.departmentCode = departmentCode;
	}
	
	public Set getAgents() {
		return this.Agents;
	}
	
	public void setAgents(Set Agents) {
		this.Agents = Agents;
	}
	
	public Set getMaintenanceRequests() {
		return this.MaintenanceRequests;
	}
	
	public void setMaintenanceRequests(Set MaintenanceRequests) {
		this.MaintenanceRequests = MaintenanceRequests;
	}
	
	public Set getEquipments() {
		return this.Equipments;
	}
	
	public void setEquipments(Set Equipments) {
		this.Equipments = Equipments;
	}
	
	@Override
	public User getCreator() {
		return creator;
	}
	
	@Override
	public void setCreator(User creator) {
		this.creator = creator;
	}
	
	@Override
	public Integer getId() {
		return getDepartmentId();
	}
	
	@Override
	public void setId(Integer id) {
		setDepartmentId(id);
	}
}
