package org.openmrs.module.savicsgmao.api.entity;

// Generated Apr 13, 2021 3:01:21 PM by Hibernate Tools 4.3.1

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {
	
	private Integer departmentId;
	
	private String uuid;
	
	private String departmentName;
	
	private String departmentCode;
	
	public Department() {
	}
	
	public Department(String uuid, String departmentName, String departmentCode) {
		this.uuid = uuid;
		this.departmentName = departmentName;
		this.departmentCode = departmentCode;
	}
	
	public Integer getDepartmentId() {
		return this.departmentId;
	}
	
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}
	
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public String getDepartmentName() {
		return this.departmentName;
	}
	
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}
	
	public String getDepartmentCode() {
		return this.departmentCode;
	}
	
	public void setDepartmentCode(String departmentCode) {
		this.departmentCode = departmentCode;
	}
	
}
