package org.openmrs.module.savicsgmao.api.entity;


import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 * District generated by hbm2java
 */
public class District extends BaseOpenmrsData  implements java.io.Serializable {

     private Integer districtId;
     private Region Region;
     private String uuid;
     private String districtName;
     private String districtCode;
     private Set SiteLocations = new HashSet(0);

    public District() {
    }

	
    public District(Region Region, String uuid, String districtName, String districtCode) {
        this.Region = Region;
        this.uuid = uuid;
        this.districtName = districtName;
        this.districtCode = districtCode;
    }
    public District(Region Region, String uuid, String districtName, String districtCode, Set SiteLocations) {
       this.Region = Region;
       this.uuid = uuid;
       this.districtName = districtName;
       this.districtCode = districtCode;
       this.SiteLocations = SiteLocations;
    }
   
    public Integer getDistrictId() {
        return this.districtId;
    }
    
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }
    public Region getRegion() {
        return this.Region;
    }
    
    public void setRegion(Region Region) {
        this.Region = Region;
    }
    
    public String getDistrictName() {
        return this.districtName;
    }
    
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }
    public String getDistrictCode() {
        return this.districtCode;
    }
    
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }
    public Set getSiteLocations() {
        return this.SiteLocations;
    }
    
    public void setSiteLocations(Set SiteLocations) {
        this.SiteLocations = SiteLocations;
    }
    
    @Override
    public User getCreator() {
        return creator;
    }

    @Override
    public void setCreator(User creator) {
        this.creator = creator;
    }

    @Override
    public Integer getId() {
        return getDistrictId();
    }

    @Override
    public void setId(Integer id) {
        setDistrictId(id);
    }
}


