package org.openmrs.module.savicsgmao.api.entity;
// Generated Apr 19, 2021 4:44:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 * Equipment generated by hbm2java
 */
public class Equipment extends BaseOpenmrsData implements java.io.Serializable {

    private Integer equipmentId;
    private Department Department;
    private EquipmentType EquipmentType;
    private String uuid;
    private String serialNumber;
    private Date acquisitionDate;
    private int equipmentStatus;
    private String designation;
    private String localization;
    private Date lastModifiedDate;
    private Float equipmentWeight;
    private Float volume;
    private Float acquisitionValue;
    private Integer tracking;
    private Byte inService;
    private Integer operatingState;
    private Integer commisionningYear;
    private String comments;
    private int providerId;
    private Set Maintenances = new HashSet(0);
    private Set MaintenanceRequests = new HashSet(0);
    private Set MaintenanceTasks = new HashSet(0);
    private Set EquipmentOperationItems = new HashSet(0);

    public Equipment() {
    }

    public Equipment(Department Department, EquipmentType EquipmentType, String uuid, String serialNumber, int equipmentStatus, String designation, String localization, String comments, int providerId) {
        this.Department = Department;
        this.EquipmentType = EquipmentType;
        this.uuid = uuid;
        this.serialNumber = serialNumber;
        this.equipmentStatus = equipmentStatus;
        this.designation = designation;
        this.localization = localization;
        this.comments = comments;
        this.providerId = providerId;
    }

    public Equipment(Department Department, EquipmentType EquipmentType, String uuid, String serialNumber, Date acquisitionDate, int equipmentStatus, String designation, String localization, Date lastModifiedDate, Float equipmentWeight, Float volume, Float acquisitionValue, Integer tracking, Byte inService, Integer operatingState, Integer commisionningYear, String comments, int providerId, Set Maintenances, Set MaintenanceRequests, Set MaintenanceTasks, Set EquipmentOperationItems) {
        this.Department = Department;
        this.EquipmentType = EquipmentType;
        this.uuid = uuid;
        this.serialNumber = serialNumber;
        this.acquisitionDate = acquisitionDate;
        this.equipmentStatus = equipmentStatus;
        this.designation = designation;
        this.localization = localization;
        this.lastModifiedDate = lastModifiedDate;
        this.equipmentWeight = equipmentWeight;
        this.volume = volume;
        this.acquisitionValue = acquisitionValue;
        this.tracking = tracking;
        this.inService = inService;
        this.operatingState = operatingState;
        this.commisionningYear = commisionningYear;
        this.comments = comments;
        this.providerId = providerId;
        this.Maintenances = Maintenances;
        this.MaintenanceRequests = MaintenanceRequests;
        this.MaintenanceTasks = MaintenanceTasks;
        this.EquipmentOperationItems = EquipmentOperationItems;
    }

    public Integer getEquipmentId() {
        return this.equipmentId;
    }

    public void setEquipmentId(Integer equipmentId) {
        this.equipmentId = equipmentId;
    }

    public Department getDepartment() {
        return this.Department;
    }

    public void setDepartment(Department Department) {
        this.Department = Department;
    }

    public EquipmentType getEquipmentType() {
        return this.EquipmentType;
    }

    public void setEquipmentType(EquipmentType EquipmentType) {
        this.EquipmentType = EquipmentType;
    }

    public String getSerialNumber() {
        return this.serialNumber;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    public Date getAcquisitionDate() {
        return this.acquisitionDate;
    }

    public void setAcquisitionDate(Date acquisitionDate) {
        this.acquisitionDate = acquisitionDate;
    }

    public int getEquipmentStatus() {
        return this.equipmentStatus;
    }

    public void setEquipmentStatus(int equipmentStatus) {
        this.equipmentStatus = equipmentStatus;
    }

    public String getDesignation() {
        return this.designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    public String getLocalization() {
        return this.localization;
    }

    public void setLocalization(String localization) {
        this.localization = localization;
    }

    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public Float getEquipmentWeight() {
        return this.equipmentWeight;
    }

    public void setEquipmentWeight(Float equipmentWeight) {
        this.equipmentWeight = equipmentWeight;
    }

    public Float getVolume() {
        return this.volume;
    }

    public void setVolume(Float volume) {
        this.volume = volume;
    }

    public Float getAcquisitionValue() {
        return this.acquisitionValue;
    }

    public void setAcquisitionValue(Float acquisitionValue) {
        this.acquisitionValue = acquisitionValue;
    }

    public Integer getTracking() {
        return this.tracking;
    }

    public void setTracking(Integer tracking) {
        this.tracking = tracking;
    }

    public Byte getInService() {
        return this.inService;
    }

    public void setInService(Byte inService) {
        this.inService = inService;
    }

    public Integer getOperatingState() {
        return this.operatingState;
    }

    public void setOperatingState(Integer operatingState) {
        this.operatingState = operatingState;
    }

    public Integer getCommisionningYear() {
        return this.commisionningYear;
    }

    public void setCommisionningYear(Integer commisionningYear) {
        this.commisionningYear = commisionningYear;
    }

    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public int getProviderId() {
        return this.providerId;
    }

    public void setProviderId(int providerId) {
        this.providerId = providerId;
    }

    public Set getMaintenances() {
        return this.Maintenances;
    }

    public void setMaintenances(Set Maintenances) {
        this.Maintenances = Maintenances;
    }

    public Set getMaintenanceRequests() {
        return this.MaintenanceRequests;
    }

    public void setMaintenanceRequests(Set MaintenanceRequests) {
        this.MaintenanceRequests = MaintenanceRequests;
    }

    public Set getMaintenanceTasks() {
        return this.MaintenanceTasks;
    }

    public void setMaintenanceTasks(Set MaintenanceTasks) {
        this.MaintenanceTasks = MaintenanceTasks;
    }

    public Set getEquipmentOperationItems() {
        return this.EquipmentOperationItems;
    }

    public void setEquipmentOperationItems(Set EquipmentOperationItems) {
        this.EquipmentOperationItems = EquipmentOperationItems;
    }

    @Override
    public User getCreator() {
        return creator;
    }

    @Override
    public void setCreator(User creator) {
        this.creator = creator;
    }

    @Override
    public Integer getId() {
        return getEquipmentId();
    }

    @Override
    public void setId(Integer id) {
        setEquipmentId(id);
    }

}
