package org.openmrs.module.savicsgmao.api.entity;

import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 * EquipmentOperationItem generated by hbm2java
 */
public class EquipmentOperationItem extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer equipmentOperationItemId;
	
	private Equipment equipment;
	
	private EquipmentOperation equipmentOperation;
	
	private String uuid;
	
	public Integer getEquipmentOperationItemId() {
		return this.equipmentOperationItemId;
	}
	
	public void setEquipmentOperationItemId(Integer equipmentOperationItemId) {
		this.equipmentOperationItemId = equipmentOperationItemId;
	}
	
	public Equipment getEquipment() {
		return this.equipment;
	}
	
	public void setEquipment(Equipment Equipment) {
		this.equipment = Equipment;
	}
	
	public EquipmentOperation getEquipmentOperation() {
		return this.equipmentOperation;
	}
	
	public void setEquipmentOperation(EquipmentOperation equipmentOperation) {
		this.equipmentOperation = equipmentOperation;
	}
	
	@Override
	public User getCreator() {
		return creator;
	}
	
	@Override
	public void setCreator(User creator) {
		this.creator = creator;
	}
	
	@Override
	public Integer getId() {
		return getEquipmentOperationItemId();
	}
	
	@Override
	public void setId(Integer id) {
		setEquipmentOperationItemId(id);
	}
	
}
