package org.openmrs.module.savicsgmao.api.entity;

// Generated Apr 13, 2021 3:01:21 PM by Hibernate Tools 4.3.1

/**
 * EquipmentOperationItem generated by hbm2java
 */
public class EquipmentOperationItem implements java.io.Serializable {
	
	private Integer equipmentOperationItemId;
	
	private String uuid;
	
	private int equipmentId;
	
	private int equipmentOperationId;
	
	public EquipmentOperationItem() {
	}
	
	public EquipmentOperationItem(String uuid, int equipmentId, int equipmentOperationId) {
		this.uuid = uuid;
		this.equipmentId = equipmentId;
		this.equipmentOperationId = equipmentOperationId;
	}
	
	public Integer getEquipmentOperationItemId() {
		return this.equipmentOperationItemId;
	}
	
	public void setEquipmentOperationItemId(Integer equipmentOperationItemId) {
		this.equipmentOperationItemId = equipmentOperationItemId;
	}
	
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public int getEquipmentId() {
		return this.equipmentId;
	}
	
	public void setEquipmentId(int equipmentId) {
		this.equipmentId = equipmentId;
	}
	
	public int getEquipmentOperationId() {
		return this.equipmentOperationId;
	}
	
	public void setEquipmentOperationId(int equipmentOperationId) {
		this.equipmentOperationId = equipmentOperationId;
	}
	
}
