package org.openmrs.module.savicsgmao.api.entity;
// Generated Apr 19, 2021 4:44:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 *EquipmentOperationn generated by hbm2java
 */
public class EquipmentOperation extends BaseOpenmrsData implements java.io.Serializable {


     private Integer equipmentOperationId;
     private String uuid;
     private String operationCode;
     private int operationType;
     private Date operationDate;
     private Integer sourceSiteId;
     private Integer destinationSiteId;
     private String reason;
     private Byte localApproval;
     private Date localApprovalDate;
     private Byte centralApproval;
     private Date centralApprovalDate;
     private Set EquipmentOperationItems = new HashSet(0);

    public EquipmentOperation() {
    }

	
    public EquipmentOperation(String uuid, String operationCode, int operationType, Date operationDate, String reason) {
        this.uuid = uuid;
        this.operationCode = operationCode;
        this.operationType = operationType;
        this.operationDate = operationDate;
        this.reason = reason;
    }
    public EquipmentOperation(String uuid, String operationCode, int operationType, Date operationDate, Integer sourceSiteId, Integer destinationSiteId, String reason, Byte localApproval, Date localApprovalDate, Byte centralApproval, Date centralApprovalDate, Set EquipmentOperationItems) {
       this.uuid = uuid;
       this.operationCode = operationCode;
       this.operationType = operationType;
       this.operationDate = operationDate;
       this.sourceSiteId = sourceSiteId;
       this.destinationSiteId = destinationSiteId;
       this.reason = reason;
       this.localApproval = localApproval;
       this.localApprovalDate = localApprovalDate;
       this.centralApproval = centralApproval;
       this.centralApprovalDate = centralApprovalDate;
       this.EquipmentOperationItems = EquipmentOperationItems;
    }
   
    public Integer getEquipmentOperationId() {
        return this.equipmentOperationId;
    }
    
    public void setEquipmentOperationId(Integer equipmentOperationId) {
        this.equipmentOperationId = equipmentOperationId;
    }
    
    public String getOperationCode() {
        return this.operationCode;
    }
    
    public void setOperationCode(String operationCode) {
        this.operationCode = operationCode;
    }
    public int getOperationType() {
        return this.operationType;
    }
    
    public void setOperationType(int operationType) {
        this.operationType = operationType;
    }
    public Date getOperationDate() {
        return this.operationDate;
    }
    
    public void setOperationDate(Date operationDate) {
        this.operationDate = operationDate;
    }
    public Integer getSourceSiteId() {
        return this.sourceSiteId;
    }
    
    public void setSourceSiteId(Integer sourceSiteId) {
        this.sourceSiteId = sourceSiteId;
    }
    public Integer getDestinationSiteId() {
        return this.destinationSiteId;
    }
    
    public void setDestinationSiteId(Integer destinationSiteId) {
        this.destinationSiteId = destinationSiteId;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Byte getLocalApproval() {
        return this.localApproval;
    }
    
    public void setLocalApproval(Byte localApproval) {
        this.localApproval = localApproval;
    }
    public Date getLocalApprovalDate() {
        return this.localApprovalDate;
    }
    
    public void setLocalApprovalDate(Date localApprovalDate) {
        this.localApprovalDate = localApprovalDate;
    }
    public Byte getCentralApproval() {
        return this.centralApproval;
    }
    
    public void setCentralApproval(Byte centralApproval) {
        this.centralApproval = centralApproval;
    }
    public Date getCentralApprovalDate() {
        return this.centralApprovalDate;
    }
    
    public void setCentralApprovalDate(Date centralApprovalDate) {
        this.centralApprovalDate = centralApprovalDate;
    }
    public Set getEquipmentOperationItems() {
        return this.EquipmentOperationItems;
    }
    
    public void setEquipmentOperationItems(Set EquipmentOperationItems) {
        this.EquipmentOperationItems = EquipmentOperationItems;
    }
    
    
    @Override
    public User getCreator() {
        return creator;
    }

    @Override
    public void setCreator(User creator) {
        this.creator = creator;
    }

    @Override
    public Integer getId() {
        return getEquipmentOperationId();
    }

    @Override
    public void setId(Integer id) {
        setEquipmentOperationId(id);
    }
}


