package org.openmrs.module.savicsgmao.api.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;

/**
 * Equipment generated by hbm2java
 */
public class Equipment extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer id;
	
	private EquipmentType equipmentType;
	
	private Site site;
	
	private String uuid;
	
	private String name;
	
	private String serialNumber;
	
	private String type;
	
	private String model;
	
	private String supplier;
	
	private String power;
	
	private Boolean aftersaleservice;
	
	private String responsibleperson;
	
	private Integer serviceStatus;
	
	private String useraffectedto;
	
	private String replacementcomponent;
	
	private Boolean manuals;
	
	private Integer commisionningYear;
	
	private Date acquisitionDate;
	
	private Double acquisitionValue;
	
	private String acquisitionMode;
	
	private Double volume;
	
	private Double weight;
	
	private String comment;
	
	private Date lastmodified;
	
	private Date creation;
	
	private Set MaintenanceRequests = new HashSet(0);
	
	private Set Mouvements = new HashSet(0);
	
	private Set Maintenances = new HashSet(0);
	
	public Equipment() {
	}
	
	public Equipment(int id, EquipmentType EquipmentType, Site Site, String uuid, String name, String serialNumber,
	    int serviceStatus, String comment) {
		this.id = id;
		this.equipmentType = EquipmentType;
		this.site = Site;
		this.uuid = uuid;
		this.name = name;
		this.serialNumber = serialNumber;
		this.serviceStatus = serviceStatus;
		this.comment = comment;
	}
	
	public Equipment(int id, EquipmentType EquipmentType, Site Site, String uuid, String name, String serialNumber,
	    String type, String model, String supplier, String power, Boolean aftersaleservice, String responsibleperson,
	    int serviceStatus, String useraffectedto, String replacementcomponent, Boolean manuals, Integer commisionningYear,
	    Date acquisitionDate, Double acquisitionValue, String acquisitionMode, Double volume, Double weight, String comment,
	    Date lastmodified, Date creation, Set MaintenanceRequests, Set Mouvements, Set Maintenances) {
		this.id = id;
		this.equipmentType = EquipmentType;
		this.site = Site;
		this.uuid = uuid;
		this.name = name;
		this.serialNumber = serialNumber;
		this.type = type;
		this.model = model;
		this.supplier = supplier;
		this.power = power;
		this.aftersaleservice = aftersaleservice;
		this.responsibleperson = responsibleperson;
		this.serviceStatus = serviceStatus;
		this.useraffectedto = useraffectedto;
		this.replacementcomponent = replacementcomponent;
		this.manuals = manuals;
		this.commisionningYear = commisionningYear;
		this.acquisitionDate = acquisitionDate;
		this.acquisitionValue = acquisitionValue;
		this.acquisitionMode = acquisitionMode;
		this.volume = volume;
		this.weight = weight;
		this.comment = comment;
		this.lastmodified = lastmodified;
		this.creation = creation;
		this.MaintenanceRequests = MaintenanceRequests;
		this.Mouvements = Mouvements;
		this.Maintenances = Maintenances;
	}
	
	@Override
	public Integer getId() {
		return this.id;
	}
	
	@Override
	public void setId(Integer id) {
		this.id = id;
	}
	
	public EquipmentType getEquipmentType() {
		return this.equipmentType;
	}
	
	public void setEquipmentType(EquipmentType EquipmentType) {
		this.equipmentType = EquipmentType;
	}
	
	public Site getSite() {
		return this.site;
	}
	
	public void setSite(Site Site) {
		this.site = Site;
	}
	
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getSerialNumber() {
		return this.serialNumber;
	}
	
	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}
	
	public String getType() {
		return this.type;
	}
	
	public void setType(String type) {
		this.type = type;
	}
	
	public String getModel() {
		return this.model;
	}
	
	public void setModel(String model) {
		this.model = model;
	}
	
	public String getSupplier() {
		return this.supplier;
	}
	
	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}
	
	public String getPower() {
		return this.power;
	}
	
	public void setPower(String power) {
		this.power = power;
	}
	
	public Boolean getAftersaleservice() {
		return this.aftersaleservice;
	}
	
	public void setAftersaleservice(Boolean aftersaleservice) {
		this.aftersaleservice = aftersaleservice;
	}
	
	public String getResponsibleperson() {
		return this.responsibleperson;
	}
	
	public void setResponsibleperson(String responsibleperson) {
		this.responsibleperson = responsibleperson;
	}
	
	public int getServiceStatus() {
		return this.serviceStatus;
	}
	
	public void setServiceStatus(int serviceStatus) {
		this.serviceStatus = serviceStatus;
	}
	
	public String getUseraffectedto() {
		return this.useraffectedto;
	}
	
	public void setUseraffectedto(String useraffectedto) {
		this.useraffectedto = useraffectedto;
	}
	
	public String getReplacementcomponent() {
		return this.replacementcomponent;
	}
	
	public void setReplacementcomponent(String replacementcomponent) {
		this.replacementcomponent = replacementcomponent;
	}
	
	public Boolean getManuals() {
		return this.manuals;
	}
	
	public void setManuals(Boolean manuals) {
		this.manuals = manuals;
	}
	
	public Integer getCommisionningYear() {
		return this.commisionningYear;
	}
	
	public void setCommisionningYear(Integer commisionningYear) {
		this.commisionningYear = commisionningYear;
	}
	
	public Date getAcquisitionDate() {
		return this.acquisitionDate;
	}
	
	public void setAcquisitionDate(Date acquisitionDate) {
		this.acquisitionDate = acquisitionDate;
	}
	
	public Double getAcquisitionValue() {
		return this.acquisitionValue;
	}
	
	public void setAcquisitionValue(Double acquisitionValue) {
		this.acquisitionValue = acquisitionValue;
	}
	
	public String getAcquisitionMode() {
		return this.acquisitionMode;
	}
	
	public void setAcquisitionMode(String acquisitionMode) {
		this.acquisitionMode = acquisitionMode;
	}
	
	public Double getVolume() {
		return this.volume;
	}
	
	public void setVolume(Double volume) {
		this.volume = volume;
	}
	
	public Double getWeight() {
		return this.weight;
	}
	
	public void setWeight(Double weight) {
		this.weight = weight;
	}
	
	public String getComment() {
		return this.comment;
	}
	
	public void setComment(String comment) {
		this.comment = comment;
	}
	
	public Date getLastmodified() {
		return this.lastmodified;
	}
	
	public void setLastmodified(Date lastmodified) {
		this.lastmodified = lastmodified;
	}
	
	public Date getCreation() {
		return this.creation;
	}
	
	public void setCreation(Date creation) {
		this.creation = creation;
	}
	
	public Set getMaintenanceRequests() {
		return this.MaintenanceRequests;
	}
	
	public void setMaintenanceRequests(Set MaintenanceRequests) {
		this.MaintenanceRequests = MaintenanceRequests;
	}
	
	public Set getMouvements() {
		return this.Mouvements;
	}
	
	public void setMouvements(Set Mouvements) {
		this.Mouvements = Mouvements;
	}
	
	public Set getMaintenances() {
		return this.Maintenances;
	}
	
	public void setMaintenances(Set Maintenances) {
		this.Maintenances = Maintenances;
	}
	
}
