package org.openmrs.module.savicsgmao.api.entity;

// Generated Apr 13, 2021 3:01:21 PM by Hibernate Tools 4.3.1

/**
 * EquipementType generated by hbm2java
 */
public class EquipementType implements java.io.Serializable {
	
	private Integer equipmentTypeId;
	
	private String uuid;
	
	private String typeName;
	
	public EquipementType() {
	}
	
	public EquipementType(String uuid, String typeName) {
		this.uuid = uuid;
		this.typeName = typeName;
	}
	
	public Integer getEquipmentTypeId() {
		return this.equipmentTypeId;
	}
	
	public void setEquipmentTypeId(Integer equipmentTypeId) {
		this.equipmentTypeId = equipmentTypeId;
	}
	
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public String getTypeName() {
		return this.typeName;
	}
	
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}
	
}
