package org.openmrs.module.savicsgmao.api.entity;

import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 * EquipmentOperationItem generated by hbm2java
 */
public class EquipmentOperationItem extends BaseOpenmrsData implements java.io.Serializable {

    private Integer equipmentOperationItemId;
    private Equipment Equipment;
    private EquipmentOperation EquipmentOperation;
    private String uuid;

    public EquipmentOperationItem() {
    }

    public EquipmentOperationItem(Equipment Equipment, EquipmentOperation EquipmentOperation, String uuid) {
        this.Equipment = Equipment;
        this.EquipmentOperation = EquipmentOperation;
        this.uuid = uuid;
    }

    public Integer getEquipmentOperationItemId() {
        return this.equipmentOperationItemId;
    }

    public void setEquipmentOperationItemId(Integer equipmentOperationItemId) {
        this.equipmentOperationItemId = equipmentOperationItemId;
    }

    public Equipment getEquipment() {
        return this.Equipment;
    }

    public void setEquipment(Equipment Equipment) {
        this.Equipment = Equipment;
    }

    public EquipmentOperation getEquipmentOperation() {
        return this.EquipmentOperation;
    }

    public void setEquipmentOperation(EquipmentOperation EquipmentOperation) {
        this.EquipmentOperation = EquipmentOperation;
    }


    @Override
    public User getCreator() {
        return creator;
    }

    @Override
    public void setCreator(User creator) {
        this.creator = creator;
    }

    @Override
    public Integer getId() {
        return getEquipmentOperationItemId();
    }

    @Override
    public void setId(Integer id) {
        setEquipmentOperationItemId(id);
    }

}
