package org.openmrs.module.savicsgmao.api.entity;

// Generated Apr 13, 2021 3:01:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.UUID;

/**
 * EquipmentOperation generated by hbm2java
 */
public class EquipmentOperation implements java.io.Serializable {
	
	private Integer equipmentOperationId;
	
	private String uuid;
	
	private String operationCode;
	
	private int operationType;
	
	private Date operationDate;
	
	private Integer sourceSiteId;
	
	private Integer destinationSiteId;
	
	private String reason;
	
	private Byte localApproval;
	
	private Date localApprovalDate;
	
	private Byte centralApproval;
	
	private Date centralApprovalDate;
	
	public EquipmentOperation() {
		uuid = UUID.randomUUID().toString();
	}
	
	public EquipmentOperation(String uuid, String operationCode, int operationType, Date operationDate, String reason) {
		this.uuid = uuid;
		this.operationCode = operationCode;
		this.operationType = operationType;
		this.operationDate = operationDate;
		this.reason = reason;
	}
	
	public EquipmentOperation(String uuid, String operationCode, int operationType, Date operationDate,
	    Integer sourceSiteId, Integer destinationSiteId, String reason, Byte localApproval, Date localApprovalDate,
	    Byte centralApproval, Date centralApprovalDate) {
		this.uuid = uuid;
		this.operationCode = operationCode;
		this.operationType = operationType;
		this.operationDate = operationDate;
		this.sourceSiteId = sourceSiteId;
		this.destinationSiteId = destinationSiteId;
		this.reason = reason;
		this.localApproval = localApproval;
		this.localApprovalDate = localApprovalDate;
		this.centralApproval = centralApproval;
		this.centralApprovalDate = centralApprovalDate;
	}
	
	public Integer getEquipmentOperationId() {
		return this.equipmentOperationId;
	}
	
	public void setEquipmentOperationId(Integer equipmentOperationId) {
		this.equipmentOperationId = equipmentOperationId;
	}
	
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public String getOperationCode() {
		return this.operationCode;
	}
	
	public void setOperationCode(String operationCode) {
		this.operationCode = operationCode;
	}
	
	public int getOperationType() {
		return this.operationType;
	}
	
	public void setOperationType(int operationType) {
		this.operationType = operationType;
	}
	
	public Date getOperationDate() {
		return this.operationDate;
	}
	
	public void setOperationDate(Date operationDate) {
		this.operationDate = operationDate;
	}
	
	public Integer getSourceSiteId() {
		return this.sourceSiteId;
	}
	
	public void setSourceSiteId(Integer sourceSiteId) {
		this.sourceSiteId = sourceSiteId;
	}
	
	public Integer getDestinationSiteId() {
		return this.destinationSiteId;
	}
	
	public void setDestinationSiteId(Integer destinationSiteId) {
		this.destinationSiteId = destinationSiteId;
	}
	
	public String getReason() {
		return this.reason;
	}
	
	public void setReason(String reason) {
		this.reason = reason;
	}
	
	public Byte getLocalApproval() {
		return this.localApproval;
	}
	
	public void setLocalApproval(Byte localApproval) {
		this.localApproval = localApproval;
	}
	
	public Date getLocalApprovalDate() {
		return this.localApprovalDate;
	}
	
	public void setLocalApprovalDate(Date localApprovalDate) {
		this.localApprovalDate = localApprovalDate;
	}
	
	public Byte getCentralApproval() {
		return this.centralApproval;
	}
	
	public void setCentralApproval(Byte centralApproval) {
		this.centralApproval = centralApproval;
	}
	
	public Date getCentralApprovalDate() {
		return this.centralApprovalDate;
	}
	
	public void setCentralApprovalDate(Date centralApprovalDate) {
		this.centralApprovalDate = centralApprovalDate;
	}
	
}
