package org.openmrs.module.savicsgmao.api.entity;

import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 * MaintenanceTask generated by hbm2java
 */
public class MaintenanceTask extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer maintenanceTaskId;
	
	private Equipment Equipment;
	
	private Maintenance Maintenance;
	
	private Planification Planification;
	
	private String uuid;
	
	private String designation;
	
	private String details;
	
	private byte executed;
	
	private int taskId;
	
	public MaintenanceTask() {
	}
	
	public MaintenanceTask(Equipment Equipment, Maintenance Maintenance, String uuid, String designation, String details,
	    byte executed, int taskId) {
		this.Equipment = Equipment;
		this.Maintenance = Maintenance;
		this.uuid = uuid;
		this.designation = designation;
		this.details = details;
		this.executed = executed;
		this.taskId = taskId;
	}
	
	public MaintenanceTask(Equipment Equipment, Maintenance Maintenance, Planification Planification, String uuid,
	    String designation, String details, byte executed, int taskId) {
		this.Equipment = Equipment;
		this.Maintenance = Maintenance;
		this.Planification = Planification;
		this.uuid = uuid;
		this.designation = designation;
		this.details = details;
		this.executed = executed;
		this.taskId = taskId;
	}
	
	public Integer getMaintenanceTaskId() {
		return this.maintenanceTaskId;
	}
	
	public void setMaintenanceTaskId(Integer maintenanceTaskId) {
		this.maintenanceTaskId = maintenanceTaskId;
	}
	
	public Equipment getEquipment() {
		return this.Equipment;
	}
	
	public void setEquipment(Equipment Equipment) {
		this.Equipment = Equipment;
	}
	
	public Maintenance getMaintenance() {
		return this.Maintenance;
	}
	
	public void setMaintenance(Maintenance Maintenance) {
		this.Maintenance = Maintenance;
	}
	
	public Planification getPlanification() {
		return this.Planification;
	}
	
	public void setPlanification(Planification Planification) {
		this.Planification = Planification;
	}
	
	public String getDesignation() {
		return this.designation;
	}
	
	public void setDesignation(String designation) {
		this.designation = designation;
	}
	
	public String getDetails() {
		return this.details;
	}
	
	public void setDetails(String details) {
		this.details = details;
	}
	
	public byte getExecuted() {
		return this.executed;
	}
	
	public void setExecuted(byte executed) {
		this.executed = executed;
	}
	
	public int getTaskId() {
		return this.taskId;
	}
	
	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}
	
	@Override
	public User getCreator() {
		return creator;
	}
	
	@Override
	public void setCreator(User creator) {
		this.creator = creator;
	}
	
	@Override
	public Integer getId() {
		return getMaintenanceTaskId();
	}
	
	@Override
	public void setId(Integer id) {
		setMaintenanceTaskId(id);
	}
}
