package org.openmrs.module.savicsgmao.api.entity;

import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 * MaintenanceTask generated by hbm2java
 */
public class MaintenanceTask extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer maintenanceTaskId;
	
	private Equipment equipment;
	
	private Maintenance maintenance;
	
	private Planification planification;
	
	private String uuid;
	
	private String designation;
	
	private String details;
	
	private byte executed;
	
	private int taskId;
	
	public Integer getMaintenanceTaskId() {
		return this.maintenanceTaskId;
	}
	
	public void setMaintenanceTaskId(Integer maintenanceTaskId) {
		this.maintenanceTaskId = maintenanceTaskId;
	}
	
	public Equipment getEquipment() {
		return this.equipment;
	}
	
	public void setEquipment(Equipment Equipment) {
		this.equipment = Equipment;
	}
	
	public Maintenance getMaintenance() {
		return this.maintenance;
	}
	
	public void setMaintenance(Maintenance Maintenance) {
		this.maintenance = Maintenance;
	}
	
	public Planification getPlanification() {
		return this.planification;
	}
	
	public void setPlanification(Planification Planification) {
		this.planification = Planification;
	}
	
	public String getDesignation() {
		return this.designation;
	}
	
	public void setDesignation(String designation) {
		this.designation = designation;
	}
	
	public String getDetails() {
		return this.details;
	}
	
	public void setDetails(String details) {
		this.details = details;
	}
	
	public byte getExecuted() {
		return this.executed;
	}
	
	public void setExecuted(byte executed) {
		this.executed = executed;
	}
	
	public int getTaskId() {
		return this.taskId;
	}
	
	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}
	
	@Override
	public User getCreator() {
		return creator;
	}
	
	@Override
	public void setCreator(User creator) {
		this.creator = creator;
	}
	
	@Override
	public Integer getId() {
		return getMaintenanceTaskId();
	}
	
	@Override
	public void setId(Integer id) {
		setMaintenanceTaskId(id);
	}
}
