package org.openmrs.module.savicsgmao.api.entity;

import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 * MaintenanceTypee generated by hbm2java
 */
public class MaintenanceType extends BaseOpenmrsData implements java.io.Serializable {

    private Integer maintenanceTypeId;
    private String uuid;
    private String typeCode;
    private String typeName;
    private Set Maintenances = new HashSet(0);

    public MaintenanceType() {
    }

    public MaintenanceType(String uuid, String typeCode, String typeName) {
        this.uuid = uuid;
        this.typeCode = typeCode;
        this.typeName = typeName;
    }

    public MaintenanceType(String uuid, String typeCode, String typeName, Set Maintenances) {
        this.uuid = uuid;
        this.typeCode = typeCode;
        this.typeName = typeName;
        this.Maintenances = Maintenances;
    }

    public Integer getMaintenanceTypeId() {
        return this.maintenanceTypeId;
    }

    public void setMaintenanceTypeId(Integer maintenanceTypeId) {
        this.maintenanceTypeId = maintenanceTypeId;
    }

    public String getTypeCode() {
        return this.typeCode;
    }

    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public Set getMaintenances() {
        return this.Maintenances;
    }

    public void setMaintenances(Set Maintenances) {
        this.Maintenances = Maintenances;
    }
    
    
    @Override
    public User getCreator() {
        return creator;
    }

    @Override
    public void setCreator(User creator) {
        this.creator = creator;
    }

    @Override
    public Integer getId() {
        return getMaintenanceTypeId();
    }

    @Override
    public void setId(Integer id) {
        setMaintenanceTypeId(id);
    }

}
