package org.openmrs.module.savicsgmao.api.entity;

// Generated Apr 13, 2021 3:01:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.UUID;

/**
 * MaintenanceRequest generated by hbm2java
 */
public class MaintenanceRequest implements java.io.Serializable {
	
	private Integer maintenanceRequestId;
	
	private String uuid;
	
	private String systemNumber;
	
	private int departmentId;
	
	private String applicantName;
	
	private String registerNumber;
	
	private Date startdate;
	
	private String natureOfWork;
	
	private Date enddate;
	
	private String motif;
	
	private int requestPriority;
	
	private int equipmentId;
	
	public MaintenanceRequest() {
            uuid = UUID.randomUUID().toString();
	}
	
	public MaintenanceRequest(String uuid, String systemNumber, int departmentId, String applicantName,
	    String registerNumber, Date startdate, String natureOfWork, String motif, int requestPriority, int equipmentId) {
		this.uuid = uuid;
		this.systemNumber = systemNumber;
		this.departmentId = departmentId;
		this.applicantName = applicantName;
		this.registerNumber = registerNumber;
		this.startdate = startdate;
		this.natureOfWork = natureOfWork;
		this.motif = motif;
		this.requestPriority = requestPriority;
		this.equipmentId = equipmentId;
	}
	
	public MaintenanceRequest(String uuid, String systemNumber, int departmentId, String applicantName,
	    String registerNumber, Date startdate, String natureOfWork, Date enddate, String motif, int requestPriority,
	    int equipmentId) {
		this.uuid = uuid;
		this.systemNumber = systemNumber;
		this.departmentId = departmentId;
		this.applicantName = applicantName;
		this.registerNumber = registerNumber;
		this.startdate = startdate;
		this.natureOfWork = natureOfWork;
		this.enddate = enddate;
		this.motif = motif;
		this.requestPriority = requestPriority;
		this.equipmentId = equipmentId;
	}
	
	public Integer getMaintenanceRequestId() {
		return this.maintenanceRequestId;
	}
	
	public void setMaintenanceRequestId(Integer maintenanceRequestId) {
		this.maintenanceRequestId = maintenanceRequestId;
	}
	
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public String getSystemNumber() {
		return this.systemNumber;
	}
	
	public void setSystemNumber(String systemNumber) {
		this.systemNumber = systemNumber;
	}
	
	public int getDepartmentId() {
		return this.departmentId;
	}
	
	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}
	
	public String getApplicantName() {
		return this.applicantName;
	}
	
	public void setApplicantName(String applicantName) {
		this.applicantName = applicantName;
	}
	
	public String getRegisterNumber() {
		return this.registerNumber;
	}
	
	public void setRegisterNumber(String registerNumber) {
		this.registerNumber = registerNumber;
	}
	
	public Date getStartdate() {
		return this.startdate;
	}
	
	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}
	
	public String getNatureOfWork() {
		return this.natureOfWork;
	}
	
	public void setNatureOfWork(String natureOfWork) {
		this.natureOfWork = natureOfWork;
	}
	
	public Date getEnddate() {
		return this.enddate;
	}
	
	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}
	
	public String getMotif() {
		return this.motif;
	}
	
	public void setMotif(String motif) {
		this.motif = motif;
	}
	
	public int getRequestPriority() {
		return this.requestPriority;
	}
	
	public void setRequestPriority(int requestPriority) {
		this.requestPriority = requestPriority;
	}
	
	public int getEquipmentId() {
		return this.equipmentId;
	}
	
	public void setEquipmentId(int equipmentId) {
		this.equipmentId = equipmentId;
	}
	
}
