package org.openmrs.module.savicsgmao.api.entity;

// Generated Apr 19, 2021 4:44:31 PM by Hibernate Tools 4.3.1

import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 * MaintenanceReason generated by hbm2java
 */
public class MaintenanceReason extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer maintenanceReasonId;
	
	private String uuid;
	
	private String reasonCode;
	
	private String reasonName;
	
	private String details;
	
	public MaintenanceReason() {
	}
	
	public MaintenanceReason(String uuid, String reasonCode, String reasonName, String details) {
		this.uuid = uuid;
		this.reasonCode = reasonCode;
		this.reasonName = reasonName;
		this.details = details;
	}
	
	public Integer getMaintenanceReasonId() {
		return this.maintenanceReasonId;
	}
	
	public void setMaintenanceReasonId(Integer maintenanceReasonId) {
		this.maintenanceReasonId = maintenanceReasonId;
	}
	
	public String getReasonCode() {
		return this.reasonCode;
	}
	
	public void setReasonCode(String reasonCode) {
		this.reasonCode = reasonCode;
	}
	
	public String getReasonName() {
		return this.reasonName;
	}
	
	public void setReasonName(String reasonName) {
		this.reasonName = reasonName;
	}
	
	public String getDetails() {
		return this.details;
	}
	
	public void setDetails(String details) {
		this.details = details;
	}
	
	@Override
	public User getCreator() {
		return creator;
	}
	
	@Override
	public void setCreator(User creator) {
		this.creator = creator;
	}
	
	@Override
	public Integer getId() {
		return getMaintenanceReasonId();
	}
	
	@Override
	public void setId(Integer id) {
		setMaintenanceReasonId(id);
	}
	
}
