package org.openmrs.module.savicsgmao.api.entity;

// Generated Dec 9, 2021 11:58:16 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;

/**
 * MaintenanceTypee generated by hbm2java
 */
public class MaintenanceType extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer id;
	
	private String uuid;
	
	private String name;
	
	private Set maintenances = new HashSet(0);
	
	public MaintenanceType() {
	}
	
	public MaintenanceType(int id, String uuid, String name) {
		this.id = id;
		this.uuid = uuid;
		this.name = name;
	}
	
	public MaintenanceType(int id, String uuid, String name, Set Maintenances) {
		this.id = id;
		this.uuid = uuid;
		this.name = name;
		this.maintenances = Maintenances;
	}
	
	@Override
	public Integer getId() {
		return this.id;
	}
	
	@Override
	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public Set getMaintenances() {
		return this.maintenances;
	}
	
	public void setMaintenances(Set Maintenances) {
		this.maintenances = Maintenances;
	}
}
