package org.openmrs.module.savicsgmao.api.entity;

// Generated Apr 13, 2021 3:01:21 PM by Hibernate Tools 4.3.1

import java.util.UUID;


/**
 * MaintenanceTask generated by hbm2java
 */
public class MaintenanceTask implements java.io.Serializable {
	
	private Integer maintenanceTaskId;
	
	private String uuid;
	
	private String designation;
	
	private String details;
	
	private byte executed;
	
	private int taskId;
	
	private int maintenanceId;
	
	private int equipementId;
	
	private Integer planificationId;
	
	public MaintenanceTask() {
            uuid = UUID.randomUUID().toString();
	}
	
	public MaintenanceTask(String uuid, String designation, String details, byte executed, int taskId, int maintenanceId,
	    int equipementId) {
		this.uuid = uuid;
		this.designation = designation;
		this.details = details;
		this.executed = executed;
		this.taskId = taskId;
		this.maintenanceId = maintenanceId;
		this.equipementId = equipementId;
	}
	
	public MaintenanceTask(String uuid, String designation, String details, byte executed, int taskId, int maintenanceId,
	    int equipementId, Integer planificationId) {
		this.uuid = uuid;
		this.designation = designation;
		this.details = details;
		this.executed = executed;
		this.taskId = taskId;
		this.maintenanceId = maintenanceId;
		this.equipementId = equipementId;
		this.planificationId = planificationId;
	}
	
	public Integer getMaintenanceTaskId() {
		return this.maintenanceTaskId;
	}
	
	public void setMaintenanceTaskId(Integer maintenanceTaskId) {
		this.maintenanceTaskId = maintenanceTaskId;
	}
	
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public String getDesignation() {
		return this.designation;
	}
	
	public void setDesignation(String designation) {
		this.designation = designation;
	}
	
	public String getDetails() {
		return this.details;
	}
	
	public void setDetails(String details) {
		this.details = details;
	}
	
	public byte getExecuted() {
		return this.executed;
	}
	
	public void setExecuted(byte executed) {
		this.executed = executed;
	}
	
	public int getTaskId() {
		return this.taskId;
	}
	
	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}
	
	public int getMaintenanceId() {
		return this.maintenanceId;
	}
	
	public void setMaintenanceId(int maintenanceId) {
		this.maintenanceId = maintenanceId;
	}
	
	public int getEquipementId() {
		return this.equipementId;
	}
	
	public void setEquipementId(int equipementId) {
		this.equipementId = equipementId;
	}
	
	public Integer getPlanificationId() {
		return this.planificationId;
	}
	
	public void setPlanificationId(Integer planificationId) {
		this.planificationId = planificationId;
	}
	
}
