package org.openmrs.module.savicsgmao.api.entity;

// Generated Dec 9, 2021 11:58:16 AM by Hibernate Tools 4.3.1

import java.util.Date;
import org.openmrs.BaseOpenmrsData;

/**
 * Mouvement generated by hbm2java
 */
public class Mouvement extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer id;
	
	private Equipment equipment;
	
	private Site siteByDestinationId;
	
	private Site siteBySourceId;
	
	private String uuid;
	
	private Integer type;
	
	private Date date;
	
	private String motif;
	
	private Date localapproval;
	
	private String localapprover;
	
	private Date centralapproval;
	
	private String centralapprover;
	
	private Date creation;
	
	private Date lastmodified;
	
	public Mouvement() {
	}
	
	public Mouvement(int id, Equipment Equipment, Site SiteByDestinationId, Site SiteBySourceId, String uuid, int type,
	    Date date, String motif) {
		this.id = id;
		this.equipment = Equipment;
		this.siteByDestinationId = SiteByDestinationId;
		this.siteBySourceId = siteBySourceId;
		this.uuid = uuid;
		this.type = type;
		this.date = date;
		this.motif = motif;
	}
	
	public Mouvement(int id, Equipment Equipment, Site SiteByDestinationId, Site SiteBySourceId, String uuid, int type,
	    Date date, String motif, Date localapproval, String localapprover, Date centralapproval, String centralapprover,
	    Date creation, Date lastmodified) {
		this.id = id;
		this.equipment = Equipment;
		this.siteByDestinationId = SiteByDestinationId;
		this.siteBySourceId = SiteBySourceId;
		this.uuid = uuid;
		this.type = type;
		this.date = date;
		this.motif = motif;
		this.localapproval = localapproval;
		this.localapprover = localapprover;
		this.centralapproval = centralapproval;
		this.centralapprover = centralapprover;
		this.creation = creation;
		this.lastmodified = lastmodified;
	}
	
	@Override
	public Integer getId() {
		return this.id;
	}
	
	@Override
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Equipment getEquipment() {
		return this.equipment;
	}
	
	public void setEquipment(Equipment Equipment) {
		this.equipment = Equipment;
	}
	
	public Site getSiteByDestinationId() {
		return this.siteByDestinationId;
	}
	
	public void setSiteByDestinationId(Site SiteByDestinationId) {
		this.siteByDestinationId = SiteByDestinationId;
	}
	
	public Site getSiteBySourceId() {
		return this.siteBySourceId;
	}
	
	public void setSiteBySourceId(Site SiteBySourceId) {
		this.siteBySourceId = SiteBySourceId;
	}
	
	@Override
	public String getUuid() {
		return this.uuid;
	}
	
	@Override
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public int getType() {
		return this.type;
	}
	
	public void setType(int type) {
		this.type = type;
	}
	
	public Date getDate() {
		return this.date;
	}
	
	public void setDate(Date date) {
		this.date = date;
	}
	
	public String getMotif() {
		return this.motif;
	}
	
	public void setMotif(String motif) {
		this.motif = motif;
	}
	
	public Date getLocalapproval() {
		return this.localapproval;
	}
	
	public void setLocalapproval(Date localapproval) {
		this.localapproval = localapproval;
	}
	
	public String getLocalapprover() {
		return this.localapprover;
	}
	
	public void setLocalapprover(String localapprover) {
		this.localapprover = localapprover;
	}
	
	public Date getCentralapproval() {
		return this.centralapproval;
	}
	
	public void setCentralapproval(Date centralapproval) {
		this.centralapproval = centralapproval;
	}
	
	public String getCentralapprover() {
		return this.centralapprover;
	}
	
	public void setCentralapprover(String centralapprover) {
		this.centralapprover = centralapprover;
	}
	
	public Date getCreation() {
		return this.creation;
	}
	
	public void setCreation(Date creation) {
		this.creation = creation;
	}
	
	public Date getLastmodified() {
		return this.lastmodified;
	}
	
	public void setLastmodified(Date lastmodified) {
		this.lastmodified = lastmodified;
	}
	
}
