package org.openmrs.module.savicsgmao.api.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 * Planificationn generated by hbm2java
 */
public class Planification extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer planificationId;
	
	private String uuid;
	
	private String designation;
	
	private String planificationCode;
	
	private Date planificationDate;
	
	private String observations;
	
	private Set MaintenanceTasks = new HashSet(0);
	
	public Planification() {
	}
	
	public Planification(String uuid, String designation, String planificationCode, Date planificationDate,
	    String observations) {
		this.uuid = uuid;
		this.designation = designation;
		this.planificationCode = planificationCode;
		this.planificationDate = planificationDate;
		this.observations = observations;
	}
	
	public Planification(String uuid, String designation, String planificationCode, Date planificationDate,
	    String observations, Set MaintenanceTasks) {
		this.uuid = uuid;
		this.designation = designation;
		this.planificationCode = planificationCode;
		this.planificationDate = planificationDate;
		this.observations = observations;
		this.MaintenanceTasks = MaintenanceTasks;
	}
	
	public Integer getPlanificationId() {
		return this.planificationId;
	}
	
	public void setPlanificationId(Integer planificationId) {
		this.planificationId = planificationId;
	}
	
	public String getDesignation() {
		return this.designation;
	}
	
	public void setDesignation(String designation) {
		this.designation = designation;
	}
	
	public String getPlanificationCode() {
		return this.planificationCode;
	}
	
	public void setPlanificationCode(String planificationCode) {
		this.planificationCode = planificationCode;
	}
	
	public Date getPlanificationDate() {
		return this.planificationDate;
	}
	
	public void setPlanificationDate(Date planificationDate) {
		this.planificationDate = planificationDate;
	}
	
	public String getObservations() {
		return this.observations;
	}
	
	public void setObservations(String observations) {
		this.observations = observations;
	}
	
	public Set getMaintenanceTasks() {
		return this.MaintenanceTasks;
	}
	
	public void setMaintenanceTasks(Set MaintenanceTasks) {
		this.MaintenanceTasks = MaintenanceTasks;
	}
	
	@Override
	public User getCreator() {
		return creator;
	}
	
	@Override
	public void setCreator(User creator) {
		this.creator = creator;
	}
	
	@Override
	public Integer getId() {
		return getPlanificationId();
	}
	
	@Override
	public void setId(Integer id) {
		setPlanificationId(id);
	}
	
}
