package org.openmrs.module.savicsgmao.api.entity;

// Generated Apr 13, 2021 3:01:21 PM by Hibernate Tools 4.3.1

import java.util.UUID;

/**
 * Region generated by hbm2java
 */
public class Region implements java.io.Serializable {
	
	private Integer regionId;
	
	private String uuid;
	
	private String regionName;
	
	private String regionCode;
	
	public Region() {
		uuid = UUID.randomUUID().toString();
	}
	
	public Region(String uuid, String regionName, String regionCode) {
		this.uuid = uuid;
		this.regionName = regionName;
		this.regionCode = regionCode;
	}
	
	public Integer getRegionId() {
		return this.regionId;
	}
	
	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
	}
	
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public String getRegionName() {
		return this.regionName;
	}
	
	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}
	
	public String getRegionCode() {
		return this.regionCode;
	}
	
	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}
	
}
