package org.openmrs.module.savicsgmao.api.entity;

// Generated Apr 19, 2021 4:44:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 * Regionn generated by hbm2java
 */
public class Region extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer regionId;
	
	private String uuid;
	
	private String regionName;
	
	private String regionCode;
	
	private Set Districts = new HashSet(0);
	
	public Region() {
	}
	
	public Region(String uuid, String regionName, String regionCode) {
		this.uuid = uuid;
		this.regionName = regionName;
		this.regionCode = regionCode;
	}
	
	public Region(String uuid, String regionName, String regionCode, Set Districts) {
		this.uuid = uuid;
		this.regionName = regionName;
		this.regionCode = regionCode;
		this.Districts = Districts;
	}
	
	public Integer getRegionId() {
		return this.regionId;
	}
	
	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
	}
	
	public String getRegionName() {
		return this.regionName;
	}
	
	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}
	
	public String getRegionCode() {
		return this.regionCode;
	}
	
	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}
	
	public Set getDistricts() {
		return this.Districts;
	}
	
	public void setDistricts(Set Districts) {
		this.Districts = Districts;
	}
	
	@Override
	public User getCreator() {
		return creator;
	}
	
	@Override
	public void setCreator(User creator) {
		this.creator = creator;
	}
	
	@Override
	public Integer getId() {
		return getRegionId();
	}
	
	@Override
	public void setId(Integer id) {
		setRegionId(id);
	}
}
