package org.openmrs.module.savicsgmao.api.entity;

// Generated Dec 9, 2021 11:58:16 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;

/**
 * Service generated by hbm2java
 */
public class Service extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer id;
	
	private Healthcenter healthcenter;
	
	private String uuid;
	
	private String name;
	
	private String code;
	
	private Date lastmodified;
	
	private Date creation;
	
	private Set Sites = new HashSet(0);
	
	public Service() {
	}
	
	public Service(int id, Healthcenter Healthcenter, String uuid, String name, String code) {
		this.id = id;
		this.healthcenter = Healthcenter;
		this.uuid = uuid;
		this.name = name;
		this.code = code;
	}
	
	public Service(int id, Healthcenter Healthcenter, String uuid, String name, String code, Date lastmodified,
	    Date creation, Set Sites) {
		this.id = id;
		this.healthcenter = Healthcenter;
		this.uuid = uuid;
		this.name = name;
		this.code = code;
		this.lastmodified = lastmodified;
		this.creation = creation;
		this.Sites = Sites;
	}
	
	@Override
	public Integer getId() {
		return this.id;
	}
	
	@Override
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Healthcenter getHealthcenter() {
		return this.healthcenter;
	}
	
	public void setHealthcenter(Healthcenter Healthcenter) {
		this.healthcenter = Healthcenter;
	}
	
	@Override
	public String getUuid() {
		return this.uuid;
	}
	
	@Override
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getCode() {
		return this.code;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	public Date getLastmodified() {
		return this.lastmodified;
	}
	
	public void setLastmodified(Date lastmodified) {
		this.lastmodified = lastmodified;
	}
	
	public Date getCreation() {
		return this.creation;
	}
	
	public void setCreation(Date creation) {
		this.creation = creation;
	}
	
	public Set getSites() {
		return this.Sites;
	}
	
	public void setSites(Set Sites) {
		this.Sites = Sites;
	}
	
}
