package org.openmrs.module.savicsgmao.api.entity;

// Generated Apr 13, 2021 3:01:21 PM by Hibernate Tools 4.3.1

import java.util.UUID;

/**
 * SiteLocation generated by hbm2java
 */
public class SiteLocation implements java.io.Serializable {
	
	private Integer siteLocationId;
	
	private String uuid;
	
	private String locationName;
	
	private String locationCode;
	
	private int districtId;
	
	public SiteLocation() {
		uuid = UUID.randomUUID().toString();
	}
	
	public SiteLocation(String uuid, String locationName, String locationCode, int districtId) {
		this.uuid = uuid;
		this.locationName = locationName;
		this.locationCode = locationCode;
		this.districtId = districtId;
	}
	
	public Integer getSiteLocationId() {
		return this.siteLocationId;
	}
	
	public void setSiteLocationId(Integer siteLocationId) {
		this.siteLocationId = siteLocationId;
	}
	
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public String getLocationName() {
		return this.locationName;
	}
	
	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}
	
	public String getLocationCode() {
		return this.locationCode;
	}
	
	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}
	
	public int getDistrictId() {
		return this.districtId;
	}
	
	public void setDistrictId(int districtId) {
		this.districtId = districtId;
	}
	
}
