package org.openmrs.module.savicsgmao.api.entity;

// Generated Dec 9, 2021 11:58:16 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;

/**
 * Site generated by hbm2java
 */
public class Site extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer id;
	
	private Service service;
	
	private String name;
	
	private String code;
	
	private String uuid;
	
	private Date lastmodified;
	
	private Date creation;
	
	private Set equipments = new HashSet(0);
	
	private Set mouvementsForDestinationId = new HashSet(0);
	
	private Set mouvementsForSourceId = new HashSet(0);
	
	public Site() {
	}
	
	public Site(int id, Service Service, String uuid) {
		this.id = id;
		this.service = Service;
		this.uuid = uuid;
	}
	
	public Site(int id, Service Service, String name, String code, String uuid, Date lastmodified, Date creation,
	    Set Equipments, Set MouvementsForDestinationId, Set MouvementsForSourceId) {
		this.id = id;
		this.service = Service;
		this.name = name;
		this.code = code;
		this.uuid = uuid;
		this.lastmodified = lastmodified;
		this.creation = creation;
		this.equipments = Equipments;
		this.mouvementsForDestinationId = MouvementsForDestinationId;
		this.mouvementsForSourceId = MouvementsForSourceId;
	}
	
	@Override
	public Integer getId() {
		return this.id;
	}
	
	@Override
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Service getService() {
		return this.service;
	}
	
	public void setService(Service Service) {
		this.service = Service;
	}
	
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getCode() {
		return this.code;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	public Date getLastmodified() {
		return this.lastmodified;
	}
	
	public void setLastmodified(Date lastmodified) {
		this.lastmodified = lastmodified;
	}
	
	public Date getCreation() {
		return this.creation;
	}
	
	public void setCreation(Date creation) {
		this.creation = creation;
	}
	
	public Set getEquipments() {
		return this.equipments;
	}
	
	public void setEquipments(Set Equipments) {
		this.equipments = Equipments;
	}
	
	public Set getMouvementsForDestinationId() {
		return this.mouvementsForDestinationId;
	}
	
	public void setMouvementsForDestinationId(Set MouvementsForDestinationId) {
		this.mouvementsForDestinationId = MouvementsForDestinationId;
	}
	
	public Set getMouvementsForSourceId() {
		return this.mouvementsForSourceId;
	}
	
	public void setMouvementsForSourceId(Set MouvementsForSourceId) {
		this.mouvementsForSourceId = MouvementsForSourceId;
	}
	
}
