package org.openmrs.module.savicsgmao.api.entity;

import org.openmrs.BaseOpenmrsData;
import org.openmrs.User;

/**
 * Task generated by hbm2java
 */
public class Task extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer taskId;
	
	private EquipmentType equipmentType;
	
	private String uuid;
	
	private String taskName;
	
	private String taskProcedure;
	
	public Integer getTaskId() {
		return this.taskId;
	}
	
	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}
	
	public EquipmentType getEquipmentType() {
		return this.equipmentType;
	}
	
	public void setEquipmentType(EquipmentType EquipmentType) {
		this.equipmentType = EquipmentType;
	}
	
	public String getTaskName() {
		return this.taskName;
	}
	
	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}
	
	public String getTaskProcedure() {
		return this.taskProcedure;
	}
	
	public void setTaskProcedure(String taskProcedure) {
		this.taskProcedure = taskProcedure;
	}
	
	@Override
	public User getCreator() {
		return creator;
	}
	
	@Override
	public void setCreator(User creator) {
		this.creator = creator;
	}
	
	@Override
	public Integer getId() {
		return getTaskId();
	}
	
	@Override
	public void setId(Integer id) {
		setTaskId(id);
	}
}
